# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ehci_pci" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ "cifs" ];
  boot.kernelModules = [ "fuse" "kvm-intel" "coretemp" ];
  boot.extraModulePackages = [ ];
  boot.kernel.sysctl."net.ipv4.tcp_keepalive_time" = 120;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/80c65a03-f885-48af-a77e-8c9708895f31";
      fsType = "ext4";
    };

  swapDevices = [ ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
